### PR TITLE
add 3 missing fields to CratesResponse

### PR DESCRIPTION
**Pull request by joseluis**
add fields: versions, keywords & categories

### CODE REVIEW

**Comment by joseluis** [comment]
These are ready to be merged too.

**Comment by theduke** [comment]
Why are they optional?

Does the API return null if they are empty?

**Comment by theduke** [comment]
Let's make then not `Option` but instead default for serde.

```rust
#[serde(default)]
field: Vec<_>

```

**Comment by joseluis** [comment]
Yeah. This field is used in at least 2 API responses, one of which doesn't include them, but another does.

I just made the requested change.

**Comment by theduke** [comment]
@joseluis thanks!

**Pull request merged**
