### PR TITLE
Cargo clippy & Rust 2018

### PR DESCRIPTION
**Pull request by Cogitri**
Will have to be rebased if #4 is merged before this.

### CODE REVIEW

**Comment by theduke** [comment]
Great!

One comment: I'd like to rename `async` to something else so we don't have to use a raw identifier.

**Comment by Cogitri** [comment]
Sure, what would you prefer? asyncclient?

**Comment by theduke** [comment]
Probably `async_client`.

**Comment by Cogitri** [comment]
Alright, mind taking another look at this?

**Comment by Cogitri** [comment]
Also, are you going to tag a new release after this @theduke?

**Comment by theduke** [comment]
@Cogitri I'll hold off on merging this for a little bit until we are one ore two more compiler versions ahead.

I'll publish a patch version right now with your other two merged PRs.

**Comment by theduke** [comment]
The reason is that I always want to support the last 3 compiler versions.

**Comment by Cogitri** [comment]
Sure, I understand. When are you going to publish the new release?

**Comment by Cogitri** [comment]
Ping @theduke

**Comment by theduke** [comment]
@Cogitri merged and published as `0.4`, sorry for the delay

**Comment by Cogitri** [comment]
Thanks! :)

**Pull request merged**
