### PR TITLE
Update to Reqwest 0.10 + Async + Proxy Support

### PR DESCRIPTION
**Pull request by zicklag**
For some reason the tests are failing for me, which is strange because it seems to actually be working when I compile `cargo-crev` with it.

### CODE REVIEW

**Comment by zicklag** [comment]
OK, I've got tests passing and I added a couple extra tests from the documentation. I also set a default user agent as requests to `crates.io` were comming back with 403's without it ( there is a possibility that is because of the proxy, but I haven't tested that ).

I moved tokio to a dev dependency because we don't use it directly except in tests. Also I updated to the newest tokio. Because of that the `compat()` calls are required in the tests to convert the `0.1` futures returned by `crates-io-api` to the `0.3` futures run by the latest Tokio.

I'm going to do a quick run to see if it isn't simple to just use Futures 0.3 for everything.

**Comment by zicklag** [comment]
Hey @stiiifff  I just integrated your async changes with my reqwest update changes. I know what you mean about those `all_crates` functions though. For some reason those are really tough for me to figure out how to migrate.

Anyway, I spent a whole ton of time working on it and I'm still kind of stuck with it, but I made a lot of progress. I've only got a couple of lifetime issues now, which you might be able to help me figure out if you have the time to take a look.

**Comment by zicklag** [comment]
Ah, with some [help on the forum](https://users.rust-lang.org/t/how-to-fix-borrowing-issue-while-returning-a-futures-0-3-stream/40308/8?u=zicklag) I was able to fix the final functions and finish off the `async` upgrade.

I think should be ready to merge.

**Comment by stiiifff** [comment]
@zicklag Awesome, kudos for finalizing this :) I did take another shot but didn't have time to complete it.

**Comment by zicklag** [comment]
Don't merge this just yet actually. I just realized that we can make the async requests more efficient by putting the client data in an `Arc` and cloning the arc instead of cloning the whole client over an over.

Additionally, in light of the limitation of async functions that take a reference to the client, I think we should refactor the functions to return futures that don't take a reference to &self. This will be a straight-forward change for me to make.

**Comment by zicklag** [comment]
OK, this should be ready now. Tests are passing behind my proxy. It would be good if somebody could test not behind a proxy just to be sure, though.

**Comment by pksunkara** [comment]
I am waiting for this to be merged and released too. /cc @theduke

**Comment by zicklag** [comment]
Yeah @theduke any chance of getting this merged? We are waiting on it for `cargo-crev`.

**Comment by theduke** [comment]
Sorry for the delay, the primary reason is that I wanted to consider having some abstraction so the crate could be used with a small http client like https://github.com/sbstp/attohttpc.

Is cargo-crev comfortable with pulling in the whole tokio stack just for http requests? (@zicklag )

**Comment by zicklag** [comment]
I think it already was until now because it has been using this crate before this PR. Is that right @dpc?

**Comment by theduke** [comment]
I think the tokio 0.2 stack has quite a lot more dependencies than 0.1, which might be a concern for cargo-crev.

I have merged this (thanks for the work) and will publish a `0.6` today after doing some cleanup / fixes because this has been lingering too long. But I'll investigate a generic client solution that allows using a leaner client for a `0.7`.

**Comment by zicklag** [comment]
That sounds good.

BTW a project that might help your produce a leaner async request solution is the [`smol`](https://docs.rs/smol/0.1.4/smol/) executor.

**Comment by theduke** [comment]
It's really about being completely independent from executors. We'd need a `HttpClient` trait that can be implemented for all kinds of clients, like reqwest, attohttpc, etc. 

There's not much reason to tie a basic API wrapper like this one to particular ecosystem.

**Comment by zicklag** [comment]
That's true.

You are going to need to implement that for at least one backend, though, right? `smol` could be useful to make some default implementation. `smol` only weighs about 40 dependencies and you could put an executor agnostic reqwest lib on top of it such as `surf` maybe.

**Comment by pksunkara** [comment]
@theduke You are right. Can you add a small feature that allows me not to use `reqwest/blocking`? I don't want to pull in tokio.

**Comment by theduke** [comment]
`0.6` is published.

**Pull request merged**
